#!/usr/bin/env python3
"""Artifact Studio pipeline smoke — W2 automation test.

Usage:
    cd backend && uv run python ../scripts/smoke_artifacts.py            # scripted chain
    cd backend && uv run python ../scripts/smoke_artifacts.py --live     # real model via caber

Scripted mode drives the REAL pipeline (Pipeline → Harness → mediator →
artifact service → workspace + DB → audit) with a dynamic scripted model
that chains calls on prior tool results — no API key needed.

--live sends a natural-language request through `caber` with the real
provider — validates the capability schemas are actually drivable by an LLM.
"""

import asyncio
import json
import sys
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "backend" / "src"))

from agentos.capabilities.builtin import register_builtin_capabilities  # noqa: E402
from agentos.config_schema import CapabilityGrant  # noqa: E402
from agentos.db import async_session_factory, init_db  # noqa: E402
from agentos.harness.loop import Harness  # noqa: E402
from agentos.harness.scripted_model import ScriptedModel, ScriptedResponse  # noqa: E402
from agentos.pipeline import InboundMessage, Pipeline  # noqa: E402

ARTIFACT_GRANTS = [
    CapabilityGrant(name=f"artifact_{n}", require_approval=False)
    for n in ("create", "inspect", "revise", "history", "restore", "adopt", "export_pdf")
]


class ArtifactChainModel(ScriptedModel):
    """Emits a fixed call sequence, but injects ids parsed from prior tool
    results — the chain a real model would follow."""

    def __init__(self, path: str) -> None:
        super().__init__(responses=[])
        self._path = path
        self._step = 0
        self._ids: dict[str, str] = {}

    async def complete(self, agent_model=None, messages=None, tools=None, **_kw):
        self._harvest(messages or [])
        step = self._step
        self._step += 1
        aid = self._ids.get("artifact_id")
        rid = self._ids.get("revision_id")

        if step == 0:
            return ScriptedResponse(
                tool_calls=[
                    {
                        "id": "c1",
                        "name": "artifact_create",
                        "args": {
                            "path": self._path,
                            "spec": {
                                "title": "Smoke Report",
                                "blocks": [
                                    {"type": "heading", "level": 1, "text": "Summary"},
                                    {"type": "paragraph", "text": "Generated by the pipeline."},
                                    {"type": "table", "header": ["K", "V"], "rows": [["ok", "1"]]},
                                ],
                            },
                        },
                    }
                ]
            )
        if step == 1:
            return ScriptedResponse(
                tool_calls=[{"id": "c2", "name": "artifact_inspect", "args": {"artifact_id": aid}}]
            )
        if step == 2:
            return ScriptedResponse(
                tool_calls=[
                    {
                        "id": "c3",
                        "name": "artifact_revise",
                        "args": {
                            "artifact_id": aid,
                            "base_revision_id": rid,
                            "ops": [
                                {
                                    "op": "append_blocks",
                                    "blocks": [{"type": "paragraph", "text": "rev2"}],
                                }
                            ],
                            "change_summary": "smoke revision",
                        },
                    }
                ]
            )
        if step == 3:
            return ScriptedResponse(
                tool_calls=[{"id": "c4", "name": "artifact_history", "args": {"artifact_id": aid}}]
            )
        if step == 4:
            return ScriptedResponse(
                tool_calls=[
                    {"id": "c5", "name": "artifact_export_pdf", "args": {"artifact_id": aid}}
                ]
            )
        return ScriptedResponse(content="Artifact smoke complete.")

    async def complete_stream(self, agent_model=None, messages=None, tools=None, **kw):
        """Harness prefers streaming when the model supports it — route to
        the same chain logic."""
        resp = await self.complete(agent_model=agent_model, messages=messages, tools=tools, **kw)
        if resp.thinking:
            yield "thinking", resp.thinking
        if resp.content:
            yield "token", resp.content
        yield "done", resp

    def _harvest(self, messages: list[dict]) -> None:
        """Pull artifact/revision ids out of prior tool-result messages."""
        for m in messages:
            if m.get("role") != "tool":
                continue
            try:
                payload = json.loads(m.get("content") or "{}")
            except (TypeError, json.JSONDecodeError):
                continue
            if isinstance(payload, dict):
                if payload.get("artifact_id"):
                    self._ids["artifact_id"] = payload["artifact_id"]
                if payload.get("revision_id"):
                    self._ids["revision_id"] = payload["revision_id"]


async def _ensure_grants(agent_id: str) -> None:
    from agentos.agent_service import get_active_config, save_agent

    async with async_session_factory() as db:
        config = await get_active_config(db, agent_id)
        if config is None:
            print(f"[smoke] agent {agent_id} not found")
            sys.exit(1)
        if config.capabilities is None:
            return  # all built-ins — artifact_* included automatically
        existing = {g.name: g for g in config.capabilities}
        missing = [g for g in ARTIFACT_GRANTS if g.name not in existing]
        if not missing:
            return
        for g in missing:
            existing[g.name] = g
        config.capabilities = list(existing.values())
        await save_agent(db, config)
        print(f"[smoke] upserted {len(missing)} artifact grants on {agent_id}")


async def run_scripted(agent_id: str) -> None:
    register_builtin_capabilities()
    await init_db()
    await _ensure_grants(agent_id)

    async def emit(event_type: str, payload: dict) -> None:
        if event_type == "tool_call":
            status = payload.get("status")
            if status == "pending":
                print(f"  [tool_call] {payload.get('capability')} — pending")
            elif status == "complete":
                result = payload.get("result", {})
                brief = json.dumps(result)[:160] if isinstance(result, dict) else str(result)[:160]
                print(f"  [tool_call] {payload.get('capability')} — complete: {brief}")
            elif status == "denied":
                print(f"  [tool_call] {payload.get('capability')} — DENIED")
        elif event_type == "message_complete":
            print(f"[done] status={payload.get('status')} turns={payload.get('total_turns')}")

    artifact_path = f"smoke/report-{uuid.uuid4().hex[:8]}.docx"

    inbound = InboundMessage(
        channel="smoke_test",
        bot_id=agent_id,
        external_user_id="smoke",
        text="artifact smoke",
        message_id=str(uuid.uuid4()),
        is_test=True,
    )
    harness = Harness(model=ArtifactChainModel(artifact_path))
    async with async_session_factory() as db:
        pipeline = Pipeline(db=db, harness=harness)
        run = await pipeline.handle_inbound(
            inbound, trigger="user_message", is_test=True, event_emitter=emit
        )

    # --- verify end state ---
    from sqlalchemy import select

    from agentos.models.artifact import Artifact, ArtifactRevision
    from agentos.models.audit import AuditRecord

    failures: list[str] = []

    async with async_session_factory() as db:
        art = (
            await db.execute(select(Artifact).where(Artifact.current_path == artifact_path))
        ).scalar_one_or_none()
        if art is None:
            failures.append(f"no artifact row for {artifact_path}")
        else:
            revs = (
                (
                    await db.execute(
                        select(ArtifactRevision).where(ArtifactRevision.artifact_id == art.id)
                    )
                )
                .scalars()
                .all()
            )
            if len(revs) != 2:
                failures.append(f"expected 2 revisions, got {len(revs)}")
            elif not any(r.source_run_id == run.id for r in revs):
                failures.append("no revision carries source_run_id")
        audits = (
            (await db.execute(select(AuditRecord).where(AuditRecord.run_id == run.id)))
            .scalars()
            .all()
        )
        artifact_audits = [a for a in audits if a.capability_name.startswith("artifact_")]
        if len(artifact_audits) < 4:
            failures.append(f"expected >=4 artifact audit rows, got {len(artifact_audits)}")
        if any(not a.allowed for a in artifact_audits):
            failures.append("an artifact call was denied")

    from agentos.config import settings

    ws = settings.workspace_root / agent_id / artifact_path
    if not ws.exists():
        failures.append(f"workspace file missing: {ws}")

    print()
    if failures:
        for f in failures:
            print(f"  FAIL {f}")
        sys.exit(1)
    print(f"[pass] run {run.id} — file, 2 revisions, provenance, audit all verified")


async def run_live(agent_id: str) -> None:
    from agentos.runner import run_agent

    register_builtin_capabilities()
    await init_db()
    await _ensure_grants(agent_id)

    async def emit(event_type: str, payload: dict) -> None:
        if event_type == "tool_call":
            status = payload.get("status")
            if status == "pending":
                print(f"  [tool_call] {payload.get('capability')} — pending")
            elif status == "complete":
                result = payload.get("result", {})
                brief = json.dumps(result)[:160] if isinstance(result, dict) else str(result)[:160]
                print(f"  [tool_call] {payload.get('capability')} — complete: {brief}")
            elif status == "denied":
                print(f"  [tool_call] {payload.get('capability')} — DENIED")
        elif event_type == "token":
            print(payload.get("content", ""), end="", flush=True)

    print(f"\n[live] asking {agent_id} to build a docx via real model...\n")
    result = await run_agent(
        agent_id,
        (
            "Use artifact_create to make live-smoke.docx (format docx) with spec "
            "{title: 'Live Smoke', blocks: [{type: 'paragraph', text: 'hello'}]}. "
            "Then call artifact_inspect on it and tell me if it's valid."
        ),
        user_id="smoke",
        is_test=False,
        event_callback=emit,
    )
    print(f"\n[live] status={result['status']} cost=${result['cost']:.4f} error={result['error']}")


if __name__ == "__main__":
    live = "--live" in sys.argv
    default_agent = "caber" if live else "test-agent"
    agent = next((a for a in sys.argv[1:] if not a.startswith("--")), default_agent)
    asyncio.run(run_live(agent) if live else run_scripted(agent))
